import Image from "next/image";
import NavBar from "@/Components/NavBar";
import Footer from "@/Components/Footer"
function Showcase() {
    return (
        <div className="text-white h-screen">
            <div className="bg-cover h-full bg-center" style={{ backgroundImage: 'url("/bg-2.png")' }}>
                <NavBar />
                <div className="z-10 text-center  gap-4 relative  mx-auto place-items-center py-16 pb-56">
                    <div className="relative">
                        <div className="absolute inset-0 bg-white bg-opacity-5 backdrop-blur-sm"></div>
                        <div className="bg-transparent relative z-10 max-w-lg  pb-4">
                            <h3 className="py-4 px-4 text-4xl font-thin text-left tracking-widest text-white mr-8">
                                Move, Collect and showcase your NFTs
                            </h3>
                            <p className="text-sm text-left px-4 tracking-wider pr-24">
                                Stay on the move, earn points through the app and get
                                your own NFT generated by our own AI using
                                your own Prompt !
                            </p>
                            <button className="bg-white hover:bg-slate-200 text-black my-8 px-16 py-4 rounded-full text-md">
                                Discover
                            </button>
                            <div className="flex flex-row justify-between px-8 space-x-6">
                                {[
                                    { label: 'NFTs', value: '13K' },
                                    { label: 'Minted', value: '9K' },
                                    { label: 'Active Users', value: '40K+' },
                                ].map((item, index) => (
                                    <div key={index} className="flex-1 bg-gray-900 text-white rounded-xl text-center p-6">
                                        <p className="text-3xl font-bold mb-2">{item.value}</p>
                                        <p className="text-sm font-thin">{item.label}</p>
                                    </div>
                                ))}
                            </div>

                        </div>
                    </div>
                    <div className=" pt-8">
                        <div className="bg-black bg-opacity-70 px-16 py-4 rounded-full p-2">

                        <div className="flex flex-row space-x-14 justify-between">
                                <a href="/moveup/">
                                    <Image
                                    src="/home.svg"
                                    alt="Profile Picture"
                                    width={50}
                                    height={50}
                                    className="rounded-2xl opacity-50"
                                /></a>
                                <a href="/moveup/performance">
                                <Image
                                    src="/performance.svg"
                                    alt="Profile Picture"
                                    width={50}
                                    height={50}
                                    className="rounded-2xl opacity-50"
                                />
                                </a>
                                <a className="place-self-center" href="/moveup/wallet">
                                <Image
                                    src="/wallet.svg"
                                    alt="Profile Picture"
                                    width={50}
                                    height={50}
                                    className="rounded-2xl opacity-50"
                                />
                                </a>
                                <a href="/moveup/nft" className="place-self-center"><Image
                                    src="/nft.svg"
                                    alt="Profile Picture"
                                    width={80}
                                    height={80}
                                    className=" opacity-50 "
                                /></a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <Footer />
        </div>
    );
}

export default Showcase;
